//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sesion5.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disposals
    {
        public int DisposalID { get; set; }
        public Nullable<int> InventoryID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> DisposalDate { get; set; }
        public string Reason { get; set; }
    
        public virtual Inventory Inventory { get; set; }
    }
}
