//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sesion5.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class useEntities : DbContext
    {
        public useEntities()
            : base("name=useEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Disposals> Disposals { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<Medications> Medications { get; set; }
        public virtual DbSet<Postavki> Postavki { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Transfers> Transfers { get; set; }
        public virtual DbSet<Warehouses> Warehouses { get; set; }
    }
}
