//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sesion5.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavki
    {
        public int ShipmentID { get; set; }
        public Nullable<int> MedicationID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual Medications Medications { get; set; }
    }
}
